---
title: "About"
editor: 
  markdown: 
    wrap: 72
---

I am Victoria Johnson, a 4th year graduate student in the University of
Minnesota's Department of Educational Psychology working with Panayiota
Kendeou. I am interested in investigating effective methods of science
communication in order to promote knowledge revision of scientific
misconceptions and reduce misinformation.

[Reading + Learning
Lab](https://edpsych.umn.edu/research/labs/reading-learning)

[CV](https://docs.google.com/document/d/13JxfeprUVO8NKdY8DWFH4XYimNWr--6crh9HnkXnE9M/edit?usp=sharing)

## Education

#### Ph.D. in Educational Psychology                       2020-Current 

#### Psychological Foundations of Education: Learning and Cognition

University of Minnesota -- Twin Cities, Minneapolis, MN

Advisor: Dr. Panayiota Kendeou

#### MA in Educational Psychology                          2020-2022 

#### Psychological Foundations of Education: Learning and Cognition

University of Minnesota -- Twin Cities, Minneapolis, MN

Advisor: Dr. Panayiota Kendeou

#### B.S. in Economics, B.A. in Psychology               2016-2020 

Duke University, Durham, NC

Advisor: Dr. Bridgette Martin Hard

## References

**Johnson, V.**, Butterfuss, R., Kim, J., Orcutt, E., Harsch, R., &
Kendeou, P. (2022). The 'Fauci Effect': Reducing COVID-19 Misconceptions
and Vaccine Hesitancy Using an Authentic Multimodal Intervention.
Contemporary Educational Psychology, 70.
<https://doi.org/10.1016/j.cedpsych.2022.102084>

Kim, J., Butterfuss, R., Choi, D.-H., Orcutt, E., **Johnson, V.**, &
Kendeou, P. (2022). The Future of Reading Comprehension: Embracing
Complexity and Expanding Theory. Routledge.
<https://doi.org/10.4324/9781138609877-REE174-1>

Orcutt, E., **Johnson, V.**, & Kendeou, P. (2022). Comprehension. In
Handbook on the Science of Early Literacy. Guilford Press.
[https://www.guilford.com/books/Handbook-on-the-Science-of-Early-Literacy/C
abell-Neuman-Terry/9781462551545](https://www.guilford.com/books/Handbook-on-the-Science-of-Early-Literacy/C abell-Neuman-Terry/9781462551545)
